FROM %BUILDTOOLSTAG%
MAINTAINER Zenoss <ian@zenoss.com>

#Install openSSH Server
RUN yum install -y openssh-server && yum clean all

# Update sshd settings
RUN sed -i 's|session    required     pam_loginuid.so|session    optional     pam_loginuid.so|g' /etc/pam.d/sshd &&\
    mkdir -p /var/run/sshd
    
# Add jenkins user    
RUN useradd -m -d /home/jenkins -s /bin/sh jenkins &&\
    echo "jenkins:jenkins" | chpasswd

# Standard SSH port
EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]